// Generated by Wrangler by running `wrangler types`

interface Env {
	ENVIRONMENT: "production";
	JWT_SECRET: "aethera_healthcare_jwt_secret_2026_secure_random_string_change_in_production";
	JWT_EXPIRY_HOURS: "24";
	ADMIN_USERNAME: "aethera";
	FRONTEND_URL: "https://aethera-crm.aetherahealthcare.workers.dev";
	API_RATE_LIMIT_REQUESTS: "1000";
	API_RATE_LIMIT_WINDOW_MS: "3600000";
	DB: D1Database;
	EMAIL: SendEmail;
}
